"""Remove author field from articles

Revision ID: 1721b3fac6ce
Revises: 89674462e20a
Create Date: 2025-10-07 22:24:34.120140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1721b3fac6ce'
down_revision: Union[str, Sequence[str], None] = '89674462e20a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('author', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
