"""add_pricing_fields_to_projects

Revision ID: 3ab9f1392b46
Revises: add_features_to_services
Create Date: 2025-10-10 01:51:13.150501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ab9f1392b46'
down_revision: Union[str, Sequence[str], None] = 'add_features_to_services'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Removed order table alterations due to SQLite limitations
    op.add_column('projects', sa.Column('estimated_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('projects', sa.Column('estimated_duration_hours', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('complexity_level', sa.Enum('SIMPLE', 'MEDIUM', 'COMPLEX', name='complexitylevel'), nullable=True))
    op.add_column('projects', sa.Column('price_range_min', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('projects', sa.Column('price_range_max', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'price_range_max')
    op.drop_column('projects', 'price_range_min')
    op.drop_column('projects', 'complexity_level')
    op.drop_column('projects', 'estimated_duration_hours')
    op.drop_column('projects', 'estimated_price')
    # Note: Removed order table alterations due to SQLite limitations
    # ### end Alembic commands ###
