"""add_images_field_to_projects

Revision ID: 87624c6328ad
Revises: 1721b3fac6ce
Create Date: 2025-10-07 23:36:18.549012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87624c6328ad'
down_revision: Union[str, Sequence[str], None] = '1721b3fac6ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('images', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'images')
    # ### end Alembic commands ###
