"""Add role and last_login to users, status and views to articles

Revision ID: ab06f40082c0
Revises: dcc065889eba
Create Date: 2025-10-08 00:39:37.363654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab06f40082c0'
down_revision: Union[str, Sequence[str], None] = 'dcc065889eba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('articles', sa.Column('views', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'role')
    op.drop_column('articles', 'views')
    op.drop_column('articles', 'status')
    # ### end Alembic commands ###
